name: links_app
description: A Flutter app that allows create lists of links.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.7
  path: ^1.8.2
  firebase_database: ^10.1.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.5.0
  shared_preferences: ^2.1.1
  google_sign_in: ^6.1.0
  string_validator: ^1.0.0
  textfield_tags: ^2.0.2
  flutter_facebook_auth: ^5.0.11

  #firebase: ^9.0.3
  
  firebase_storage: ^11.2.3
  cloud_firestore: ^4.8.1

  #file_picker: ^4.6.1
 # dio: ^4.0.6
  image_picker: ^0.8.9

  mime_type: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
